name = "Hammer"
author = "WaffleIBOT"
version = "1.13.2+1.21.3.neoforge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1fc5a150723f65ddbbab631f1e859e16633a964ab0e8c2af0a501883c4d70131"

[versions]
minecraft = "1.21.3"
neoforge = "21.3.57"

[options]
acceptable-game-versions = ["1.21.2"]
