name = "Hammer"
author = "WaffleIBOT"
version = "1.12.0+1.21.3.neoforge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6c24045700c3df375b2957127d4130a214d1e74de602694b84a1117b747b568f"

[versions]
minecraft = "1.21.3"
neoforge = "21.3.11-beta"

[options]
acceptable-game-versions = ["1.21.2"]
