name = "Hammer"
author = "WaffleIBOT"
version = "1.11.1+1.21.3.neoforge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fa6a2a689c1145fddee66d863b55d5bfaa8d4c6e7694b1129b82ce48f0e8f967"

[versions]
minecraft = "1.21.3"
neoforge = "21.3.6-beta"

[options]
acceptable-game-versions = ["1.21.2"]
