name = "Hammer"
author = "WaffleIBOT"
version = "1.13.1+1.21.3.neoforge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "830f26cf1ae1eb458b45a543aa95a6cc5a92b31a665e6a637bf8658c18ff4ae3"

[versions]
minecraft = "1.21.3"
neoforge = "21.3.57"

[options]
acceptable-game-versions = ["1.21.2"]
