name = "Hammer"
author = "WaffleIBOT"
version = "1.13.2+1.21.3.neoforge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e70ed5d519a206e5b9bbe1b08304500fc612e7e0cbd3dadc948a8a663b88aff3"

[versions]
minecraft = "1.21.3"
neoforge = "21.3.58"

[options]
acceptable-game-versions = ["1.21.2"]
