name = "Hammer"
author = "WaffleIBOT"
version = "1.12.1+1.21.3.neoforge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5af84973c9f00cd9322a8387e477ebeef17efac39a02d9ed2f94acb173423361"

[versions]
minecraft = "1.21.3"
neoforge = "21.3.51-beta"

[options]
acceptable-game-versions = ["1.21.2"]
