name = "Hammer"
author = "WaffleIBOT"
version = "1.13.4+1.21.3.neoforge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b56f438c4ea61a2bd23f6788bb49651dc55934d7bc150a1dccd914e3573275be"

[versions]
minecraft = "1.21.3"
neoforge = "21.3.58"

[options]
acceptable-game-versions = ["1.21.2"]
