name = "Hammer"
author = "WaffleIBOT"
version = "1.13.0+1.21.1.neoforge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ea40bd5ae558da8cc2b8fa92269c8b09c9906009cae3c123a07050c5068d5e73"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.83"

[options]
acceptable-game-versions = ["1.21"]
