name = "Hammer"
author = "WaffleIBOT"
version = "1.12.1+1.21.1.neoforge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ea9b2624d6868656c4c594b1dddc07bcb84fb3bf1bffebd3b02b0b88a20499b3"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.83"

[options]
acceptable-game-versions = ["1.21"]
