name = "Hammer"
author = "WaffleIBOT"
version = "1.8.3+1.21.1.neoforge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c520a8ab290182247493e5e7255124ece2aeffe2716509e7759cb17775276977"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.51"

[options]
acceptable-game-versions = ["1.21"]
