name = "Hammer"
author = "WaffleIBOT"
version = "1.10.1+1.21.1.neoforge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "556edc84d733be3daf2af9ff4f20936d5cc7be2c353242b870bf027d63eafdd4"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.72"

[options]
acceptable-game-versions = ["1.21"]
