name = "Hammer"
author = "WaffleIBOT"
version = "1.13.2+1.21.1.neoforge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "95ce60a6d4dddd8cd74d7e2c44ac05fbcbdd0a5cfba44eff146b20636d222f41"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.84"

[options]
acceptable-game-versions = ["1.21"]
