name = "Hammer"
author = "WaffleIBOT"
version = "1.13.2+1.21.4.neoforge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3c415fb1ce79f3a2b6c3aedb2eebeb0de47005ec4cfcbc895de2cfccc1c49c41"

[versions]
minecraft = "1.21.4"
neoforge = "21.4.30-beta"
