name = "Hammer"
author = "WaffleIBOT"
version = "1.13.1+1.21.4.neoforge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "68e267ab661d468f2c245f979c594c33002339a7b0b69b7c7322aed73a2c9d5c"

[versions]
minecraft = "1.21.4"
neoforge = "21.4.10-beta"
