name = "Hammer"
author = "WaffleIBOT"
version = "1.13.3+1.21.4.neoforge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ad93aecf136663b8bf5cf22c0fe6b7f0eebb0ffbcc5f28179a957d283981ba37"

[versions]
minecraft = "1.21.4"
neoforge = "21.4.30-beta"
