name = "Hammer"
author = "WaffleIBOT"
version = "1.12.1+1.20.1.neoforge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fb9cbff07ba75cd0a5119b7ca1ed6f7d63daf2a2d690aa46b7aadcc8522c67ed"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
