name = "Hammer"
author = "WaffleIBOT"
version = "1.13.1+1.20.1.neoforge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3a2185d315898e67b208989293820114a36d478b7a6f9eadf6748abe81c17a32"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"

[options]
acceptable-game-versions = ["1.20"]
