name = "Hammer"
author = "WaffleIBOT"
version = "1.13.2+1.20.1.neoforge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "05939ad8f013174994f03dae8a35998336fd3e9e4cd6a7296e5ba6bccc2be1ea"

[versions]
forge = "47.3.12"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
