name = "Hammer"
author = "WaffleIBOT"
version = "1.12.2+1.20.1.neoforge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1f6f373fd470f466bdec5a4715ff27187c86f5e1e8aa7e1b18dfbbfa1ebf236a"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
