name = "Hammer"
author = "WaffleIBOT"
version = "1.11.1+1.20.4.neoforge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5579e71d5ce79420d52c317e59c0f005e692be4f948f3c5f3e2c282d9d968672"

[versions]
minecraft = "1.20.4"
neoforge = "20.4.237"
