name = "Hammer"
author = "WaffleIBOT"
version = "1.10.0+1.20.4.neoforge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "405880225f78d041a0c62dea3726dddaf4b0d6efe0514b2eda5a0ad840f15de4"

[versions]
minecraft = "1.20.4"
neoforge = "20.4.237"
